### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Xh0st** [raghavkhanna30/Telegram-Scraper#7]
Traceback (most recent call last):
  File "C:\Users\andan\Desktop\Telegram-Scraper\setup.py", line 99, in <module>
    if any ([sys.argv[1] == '--config', sys.argv[1] == '-c']):
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andan\Desktop\Telegram-Scraper\setup.py", line 125, in <module>
    print('\n'+gr+'['+re+'!'+gr+']'+cy+' no argument given : '+ sys.argv[1])
IndexError: list index out of range

**Comment by solokings** [comment]
> Traceback (most recent call last):
> File "C:\Users\andan\Desktop\Telegram-Scraper\setup.py", line 99, in
> if any ([sys.argv[1] == '--config', sys.argv[1] == '-c']):
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\andan\Desktop\Telegram-Scraper\setup.py", line 125, in
> print('\n'+gr+'['+re+'!'+gr+']'+cy+' no argument given : '+ sys.argv[1])
> IndexError: list index out of range

I encountered the same issue.  How did you go about it

**Comment by that-sami** [comment]
you forgot the -c at the end
